### ISSUE TITLE
why do you use Elastic search

### ISSUE THREAD

**Issue by HelloTo4x** [VirtoCommerce/vc-module-elastic-app-search#16]
Hi all, do anyone know what difference between Elastic search and Solr, why do u need elastic search in this project, why don't use Solr

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8070 has been created

**Comment by Woland2k** [comment]
We actually have several search providers available, including lucena, azure search, elastic search, elastic search app and algolia. We prefer elastic search, as it offers easy scalability and advanced features. However, SOLR provider can be easily added and we have some partner who did implement SOLR as part of the solution.

**Comment by HelloTo4x** [comment]
can u tell me about "advanced features" you think it only on Elastic search, and not have in other libraries.

**Comment by Woland2k** [comment]
Advanced features that Elastic Search offers that we use extensively are:

- Easy On-demand scalability (simply adding new instances to the cluster allows us to scale ES to handle more traffic)
- Multi-tenancy support that allows us to run single ES for multiple clients
- ES Cloud, some of our clients prefer to have their own cloud instance
- Filtered aggregations, which allow us to personalize pricing filters based on the customer account and assigned price lists

And for Elastic AppSearch we use the following:

- Curated search results, which allow customers to specify exact results for certain queries
- Search Analytics (I know this is is supported by many other search engines like Algolia)
- UI to manage search prioritization

**Comment by HelloTo4x** [comment]
thank u so much
